### ISSUE TITLE
Current merge script does not work

### ISSUE THREAD

**Issue by Hang-Bobby-Zou** [SiEPIC/UBC-ELEC413-2023#102]
The current merge script "UBC_ELEC413_TLDS_resonator" does not work due to:

1. Cell naming issues for cell "cell_y", "cell_pad", "cell_gcA", "cell_laser" in the "SiEPICfab_EBeam_ZEP" library
2. No matching cell for "cell_gcB" in the "SiEPICfab_EBeam_ZEP"

Once fixed these issues locally, the script throws the following error (attached):
![image](https://github.com/SiEPIC/UBC-ELEC413-2023/assets/45744171/05189cb8-6290-4039-b7f9-6c1f7b9da9c3)

Using up-to-date ZEP library and siepic_tools library (Aug 1 2023)

**Comment by lukasc-ubc** [comment]
fixed. can you please check?

**Comment by Hang-Bobby-Zou** [comment]
Verified Fixed. Closing the Issue
